AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'apimdemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'apim-bob-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://github.com/RobertoBorges'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'
