# Base pipeline to deploy APIM ESLZ with default configuration
# Instructions:
# 1) Create a service connection in Azure Devops to Github so the remote repo where the Bicep files
#    of APIM- ESLZ are located can be downloaded
# 2) Enter the correct name of the APIM- ESLZ repo and the name of the just created 
#    service endpoint for the Github on lines 22 and 23
# 3) Substitute all variable values in the connected template apim-eslz-vars.yml 
#    to align with your environment

trigger: none

resources:
  repositories:
  - repository: apimeslz
    type: github
    name: RobertoBorges/apim-landing-zone-accelerator
    endpoint: 'RobertoBorges (1)'

stages:
  - stage: validate_bicep
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: apim-eslz-vars-dev
    displayName: 'Fetch templates from github and validate '
    jobs:
      - job: validate_bicep
        displayName: Validate Bicep files
        steps:
          - checkout: apimeslz

          - task: AzureCLI@2
            displayName: Validate bicep against the subscription 
            inputs:
              azureSubscription: azure-pfeborges-subscription
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: | 
                
                echo validating bicep

                az deployment sub validate --location $(deploymentLocation) --output table --template-file main.bicep --parameters workloadName=$(workloadName) environment=$(environment) vmUsername=$(vmUsername) vmPassword=$(vmPassword) accountName=$(sourceControlaccountName) personalAccessToken=$(personalAccessToken) CICDAgentType=$(CICDAgentType) appGatewayFqdn=$(appGatewayFqdn) certificatePassword=$(certificatePassword) appGatewayCertType=$(appGatewayCertType)
              workingDirectory: './reference-implementations/AppGW-IAPIM-Func/bicep'

  - stage: build_and_deploy
    displayName: 'Deploy all bicep artifacts'
    dependsOn: validate_bicep
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: apim-eslz-vars-dev
    jobs:
      - deployment: 
        displayName: 'Deploy APIM ESLZ artifacts to Azure subscription'
        environment: apim-dev
        strategy:
         runOnce:
           deploy:
             steps:
             
              - checkout: apimeslz
            
              - task: AzureCLI@2
                displayName: Deploy azure resources
                inputs:
                  azureSubscription: azure-pfeborges-subscription
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: | 
                    
                    echo "Deploying to $(deploymentLocation) with name prefix $(workloadName) and environment tag $(environment)"

                    az deployment sub create --name APIM-$(workloadName)-$(environment) --no-wait --location $(deploymentLocation) --template-file main.bicep --parameters workloadName=$(workloadName) environment=$(environment) vmUsername=$(vmUsername) vmPassword=$(vmPassword) accountName=$(sourceControlaccountName) personalAccessToken=$(personalAccessToken) CICDAgentType=$(CICDAgentType) appGatewayFqdn=$(appGatewayFqdn) certificatePassword=$(certificatePassword) appGatewayCertType=$(appGatewayCertType)
                  
                    echo "Deployment triggered, check the status under deployment on the subscriptions $(az account show --query 'name') with deployment name APIM-$(workloadName)-$(environment)"
                  workingDirectory: './reference-implementations/AppGW-IAPIM-Func/bicep'
